### ISSUE TITLE
A logic error

### ISSUE THREAD

**Issue by linuxaged** [KhronosGroup/KTX#25]
in _ktxCheckHeader function (checkheader.c):

		if (header->glTypeSize != 1 ||
			header->glTypeSize != 2 ||
			header->glTypeSize != 4)
		{
			/* Only 8, 16, and 32-bit types supported so far */
			return KTX_INVALID_VALUE;
		}

i think this will be alway true.
use '&&' instead ?

**Comment by msc-** [comment]
You're right!! Thanks. Fixed in commit https://github.com/KhronosGroup/KTX/commit/3b3e794ac6f406aa8b3e02ecb1d1d39c22c8c276 on master and https://github.com/KhronosGroup/KTX/commit/3a47eb967684de5c6ab3b3a06ee75f706bbd6f99 on incoming.

I'll open a new issue to remind me to create a big-endian KTX file.
