### ISSUE TITLE
Problem of generating MSVS projects through GYP

### ISSUE THREAD

**Issue by subdivider** [KhronosGroup/KTX#27]
Hello, I decided to use Mali OpenGL ES Emulator so I edited "gyp_include\config.gypi" and then run three commands:
```
gyp -f msvs -G msvs_version=2015 --generator-output=build/msvs
--depth=. libktx.gyp
gyp -f msvs -G msvs_version=2015 --generator-output=build/msvs
--depth=. ktxtools.gyp
gyp -f msvs -G msvs_version=2015 --generator-output=build/msvs
--depth=. ktxtests.gyp
'ls' is not recognized as an internal or external command,
operable program or batch file.
gyp: Call to 'ls testimages/*.ktx' returned exit status 1 while in ktxtests.gyp.
```
First two commands run OK and generated required projects/solutions, but the 3rd one end up with stated error. I don't know, if this issue is GYP related, or there is some problem with file 'tests/tests.gypi'...
p.s.: My system is Win 8.1 and I have used master branch of GYP and Python 2.7.12. I run those commands from VS2015 x86 Native Tools Command Prompt...

**Comment by msc-** [comment]
'ls' is used in a command expansion (<!) of a GYP variable. The problem is that the Windows command prompt does not have an ls command. Try PowerShell instead. Note I have not tried this myself but I do know that PS has an 'ls' command. Alternatives that are known to work are the Git for Windows bash shell (recommended) or a Cygwin bash shell.

Don't forget to set your desired 64- or 32-bit build in maliemu.gypi as the generated project will only be able to build one of them.

**Comment by subdivider** [comment]
Thank You for Your suggestions!
